### ISSUE TITLE
experimental: reduce number of templates (centos70*)?

### ISSUE THREAD

**Issue by kontrafiktion** [boxcutter/centos#2]
I did an experiment, reducing the number of templates (thereby making the templates and scripts somewhat more complicated): https://github.com/kontrafiktion/centos/tree/redux70

the centos70, centos70-desktop, and centos70-docker templates are mostly identical.
They only differ in some variable values (disk_size, mem_size, vm_name), but the builders themselves are nearly identical. 
All variants execute the same shell scripts which now check for an environment variable (INSTALL_DOCKER, INSTALL_DESKTOP).
The only real difference left ist the vagrant template: it is only used in the desktop variant, but that could be eliminated as well by using a much simpler template for the other two variants.

I am not sure, if this simplifies or complicates things, but I never like copy and paste.

I did not delete the templates and did not yet adapt the makefile, just wanted to get some feedback

**Comment by annawake** [comment]
Addressed by https://github.com/boxcutter/centos/commit/18a392bbf82b91fe92c0d377d6a75ce8a8ef1af9 DRY up through `-var-file`
