### ISSUE TITLE
Missing vmware-tools in v2.0.3(vmware_desktop,minimal)

### ISSUE THREAD

**Issue by ufuchs** [boxcutter/centos#23]
Hello and many thanks for this great work.
In v2.0.3 loading the HGFS kernel module failed and the folder /lib/vmware-tools is missing.
Best regards,Uli
PS: installed via 'vagrant init boxcutter/centos71; vagrant up --provider vmware_desktop'

**Comment by annawake** [comment]
It's likely that you are trying to use VMware Fusion 7 or VMware Workstation 10 to build these templates when they only support building on VMware Fusion 8/11.  You can either wait for the workaround that was posted over in the ubuntu version of the templates to be ported here, or migrate it yourself https://github.com/boxcutter/ubuntu/commit/bceb01cd8040c8cd7b3dec8bb1f07a77c93aca91

**Comment by ufuchs** [comment]
Hello and, I wasn't idle all the time. Cloning into 'boxcutter/centos' and building an own box wasn't an option. But using this workaround solved the problem for the moment:
https://github.com/craigwatson/puppet-vmwaretools/issues/55
I'm using Fusion 8 and the 'vagrant-vmware-fusion (4.0.1)' plugin.
