### ISSUE TITLE
Makefile.local settings being ignored

### ISSUE THREAD

**Issue by n2ygk** [boxcutter/centos#32]
Somewhere between 1.0.14 and 2.0.8 the Makefile.local overrides started being ignored as a result of refactoring the Makefile to invoke bin/box/build. However the README.md still documents it.
See example below:

```
centos$ cat Makefile.local 
CM = puppet
centos$ make -n build
bin/box build centos510-i386.json
bin/box build centos510.json
bin/box build centos511-i386.json
bin/box build centos511.json
bin/box build centos64-desktop.json
bin/box build centos64-i386.json
bin/box build centos64.json
bin/box build centos65-desktop.json
bin/box build centos65-docker.json
bin/box build centos65-i386.json
bin/box build centos65.json
bin/box build centos66-desktop.json
bin/box build centos66-docker.json
bin/box build centos66-i386.json
bin/box build centos66.json
bin/box build centos67-desktop.json
bin/box build centos67-docker.json
bin/box build centos67-i386.json
bin/box build centos67.json
bin/box build centos70-desktop.json
bin/box build centos70-docker.json
bin/box build centos70.json
bin/box build centos71-desktop.json
bin/box build centos71-docker.json
bin/box build centos71.json
```

The `-var 'cm=puppet'` option is not being based to packer.

Also the ability to use build one distro and provider only (had been `make virtualbox/centos71`) seems to have been dropped.

Workaround is to just use packer directly:

```
packer build -only=virtualbox-iso -var-file=centos71.json -var "version=`cat VERSION`" -var "cm=puppet" -var "update=true" centos.json
```

**Comment by patrick-hill** [comment]
Just an FYI here,
Why not switch to calling packer directly?
I used the variables section of the centos.json file see which variables I
needed to add to my centos67.json. Then I created the following alias in my
profile and haven't looked back:

```
alias packcentos=func_packcentos
func_packcentos() {
  packer build -only=virtualbox-iso -var-file=${1} centos.json
}
```

Then I launch with:

```

packcentos centos67.json
```

Hope this might help ;)

**Comment by n2ygk** [comment]
If one edits the centos.json then a merge conflict might happen when doing a later pull. I like externalizing the options in Makefile.local.

**Comment by patrick-hill** [comment]
I don't edit the centos.json, I copy and edit the centos67.json and
personalize it to my needs (which was really just a few variables). Then no
conflicts and easy upgrade path and still faster than running make!

**Comment by annawake** [comment]
The Makefile.local options are being phased out in favour of the `bin/box` script.  It was an omission that the documentation wasn't updated to reflect this.
