### ISSUE TITLE
VMware guest customizations fail due to lack of perl

### ISSUE THREAD

**Issue by ryanl-ee** [boxcutter/centos#35]
Hi all, not sure what (if anything) can be done due to the circumstances, but here goes:

I've been using the vmware-desktop boxes, extracting them, and importing them into vSphere for use with Terraform. The Ubuntu boxes work correctly, but I tried doing the same with CentOS but it failed the guest customization. The logs show it failed because `perl` is required but is removed by Packer after the guest tools are installed. I booted up the template, installed perl, and guest customizations are now succeeding. 

I guess since these boxes are created for use in Vagrant (and by extension specifically the vmware-desktop driver) making them compatible with ESXi is out of scope, but just thought I'd bring this up and get some feedback from you.

**Comment by annawake** [comment]
Makes sense to leave behind Perl for VMware
