### ISSUE TITLE
update request for CentOS 7.2 images on AtlasCorp

### ISSUE THREAD

**Issue by wetfeet2000** [boxcutter/centos#39]
Hello, I appreciate everyone's work on all these boxes. I am currently using the CentOS 7.2 vagrant image here (https://atlas.hashicorp.com/boxcutter/boxes/centos72/) and am noticing that each time I run vagrant up VirtualBox recompiles the Guest Additions to 5.0.16. I'm hoping whoever controls these images can update them to the latest VBox Guest Additions and run a yum update. Thanks in advance!

**Comment by annawake** [comment]
Done
