### ISSUE TITLE
ISO path overrides no longer working

### ISSUE THREAD

**Issue by jrosengren** [boxcutter/centos#6]
```
$ cat Makefile.local
CENTOS66_X86_64 = /Volumes/Drobo/annex/iso/CentOS-6.6-x86_64-bin-DVD1.iso
```

```
$ make virtualbox/centos66
rm -rf output-virtualbox-iso
mkdir -p box/virtualbox
packer build -only=virtualbox-iso -var 'cm=nocm' -var 'headless=' -var 'update=' -var 'version=1.0.13' -var 'ssh_username=vagrant' -var 'ssh_password=vagrant' -var 'install_vagrant_key=true' -var 'iso_path=iso' centos66.json
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: file:///iso/CentOS-6.6-x86_64-bin-DVD1.iso
    virtualbox-iso: Error downloading: open /iso/CentOS-6.6-x86_64-bin-DVD1.iso: no such file or directory
    virtualbox-iso: Downloading or copying: http://mirrors.kernel.org/centos/6.6/isos/x86_64/CentOS-6.6-x86_64-bin-DVD1.iso
```

The Makefile is setting ISO_PATH to the following:

```
ISO_PATH ?= iso
```

It appears that since the inclusion of this environment variable, there was no glue written to tie the ISO overrides to the ISO_PATH

**Comment by annawake** [comment]
Indeed, there are no more individual overrides - instead just dump all your ISOs into that single iso path and use the ISO_PATH define instead.  Using one PATH simplified the Makefile considerably, per https://github.com/box-cutter/ubuntu-vm/issues/38 and we couldn't figure out a way to keep the individual overrides and retain the simplification.

In your example, just do the following instead:
ISO_PATH = /Volumes/Drobo/annex/iso

**Comment by jrosengren** [comment]
Ah, makes sense - I just couldn't find the Github issue or any documentation about the change.

Thank you!
