### ISSUE TITLE
box-cutter/centos67 - vsn >=2.0.17 Problems

### ISSUE THREAD

**Issue by aingham** [boxcutter/centos#61]
Hi - I've been using box-cutter/centos67 up to version 2.0.16 successfully, but from 2.0.17 onwards it fails to boot using Vagrant (so I've had to fix at 2.0.16 for now):

```
==> Booting VM...
==> Waiting for machine to boot. This may take a few minutes...
    SSH address: 127.0.0.1:2222
    SSH username: vagrant
    SSH auth method: private key
Timed out while waiting for the machine to boot.
```

I'm going to look through the 2.0.16 vs 2.0.17 diffs now, but any idea what the problem might be? FYI I'm using:

Vagrant 1.9.0
VirtualBox 5.1.10
Windows 10
Vagrant windows nfs plugin

Any help much appreciated.

**Comment by willrowe** [comment]
I'm having the same problem with `boxcutter/centos68` v2.0.21.
I can confirm that it works in v2.0.16 and not v2.0.17. Thanks for the tip @aingham!

Vagrant v1.9.1
VirtualBox v5.0.28
MacOS v10.11.6

**Comment by misheska** [comment]
There were numerous bugs in VirtualBox and/or Vagrant for months around the beginning of the year. Looks like they should be sorted now.
