### ISSUE TITLE
RHEL?

### ISSUE THREAD

**Issue by mrjcleaver** [boxcutter/centos#73]
Hi - are these templates also workable for Red Hat Enterprise Linux?

Thanks, Martin

**Comment by misheska** [comment]
Sure AFAIK.

**Comment by mrjcleaver** [comment]
Best to include RHEL and Redhat in the Readme then.

Maybe also work towards building a testing harness for them?

**Comment by mrjcleaver** [comment]
And whoever plans the Boxcutter project might want to think about how this represented as a boxcutter/separate-redhat-project.

Maybe fork and keep merging changes back in.

**Comment by misheska** [comment]
Boxcutter project doesn't currently have access to RHEL media or a subscription.

**Comment by mrjcleaver** [comment]
I'd think that Redhat would/should be keen to provide one. Just a matter of pitching it to the right person.

**Comment by patrick-hill** [comment]
I can confirm swapping to a RHEL iso works just fine.

**Comment by punkrokk** [comment]
Also - RH has free developers licenses

**Comment by punkrokk** [comment]
Just need to register
