### ISSUE TITLE
How to change the user and password?

### ISSUE THREAD

**Issue by staticfrost** [boxcutter/centos#77]
Hey,

How does one change it from being vagrant vagrant? ... 

"ssh_password"
"ssh_username" 

doesn't actually work

**Comment by misheska** [comment]
No, that doesn't work. I think we tried to easily parameterize this with older versions of packer and it wasn't straightforward.

There's a few hardcoded password references in the main template that would be changed:
https://github.com/boxcutter/centos/blob/master/centos.json#L126
https://github.com/boxcutter/centos/blob/master/centos.json#L147

And you would also need to change the username/passwords in the kickstart:
There's a user block in the kickstart that would need to be changed:
https://github.com/boxcutter/centos/blob/master/kickstart/centos7/ks.cfg#L26
The username would need to be changed at the block at the end that adds vagrant to the sudoers: https://github.com/boxcutter/centos/blob/master/centos.json#L147

That should basically be it. Though I may have left out some other places.
