### ISSUE TITLE
Virtualbox VM GUI remains black

### ISSUE THREAD

**Issue by aristosvo** [boxcutter/centos#79]
I've played a bit around with Packer and Virtualbox, but while vagrant ssh works as expected, the GUI remains black. 

My Vagrantfile looks like this
```
Vagrant.configure("2") do |config|
  config.vm.box = "centos7-desktop"
  config.vm.box_version = "0"
  config.vm.hostname = "centos-dev"
  config.vm.synced_folder '.', '/vagrant', type: :virtualbox

  config.vm.provider :virtualbox do |vb|
    vb.name = "centos-dev"
    vb.gui = true
    vb.cpus = 2
    vb.memory = 4096
  end

  #config.vm.provision "shell", inline: <<-SHELL
  #	sudo yum -y groupinstall "GNOME Desktop"
  #	sudo systemctl set-default graphical.target
  #	sudo systemctl start graphical.target
  #SHELL
end
```

**Comment by yokall** [comment]
I am experiencing this as well, seems to be when centos was upgraded to 7.5.  Interestingly while packer is building the GUI works fine, it's when I vagrant up with a new build there is an issue.

UPDATE: I updated virtualbox to the latest version (5.2.18 at the time of writing) and this seems to have resolved the issue
